adjective1 = input(" Type an adjective")
noun1 = input(" Type an Noun")
action1 = input(" Type an action")
emotion1 = input("Type an emotion")
class1 = input(" Type a class")
name1 = input(" Type a name")
noun2 = input(" Type a a noun")
name2 = input(" Type a name")
name3 = input(" Type a name for the main character")
action2 = input(" Type an action")
noun3 = input(" Type a noun")
adjective2 = input(" Type an adjective")
lesson1 = input(" Type a Lesson")
action3 = input(" Type an action")
print(f"""Once upon a time there was a {adjective1} {noun1} named {name3}.""")
print(f"""{noun1} walked through the hall, so they waved to their friend, {name2} to which they {action1}.""")
print(f"""{noun1} felt very {emotion1}, but they had to go to class, the class being {class1}.""")
print(f""" When walking to {class1}, they saw their best friend {name1}, the {noun2}.""")
print(f"""{name1} couldn't stop {action2} so {name3} decided to pay attention to {lesson1} by a forgetable teacher.""")
print(f"""{name3} needed to get out that class, so they {action3} to get detention. While walking to detention, they saw an escape route through {noun3}, leaving that {adjective2} school.""")